# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
        
name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Sonatype CLM for Maven
      run: mvn com.sonatype.clm:clm-maven-plugin:evaluate -Dclm.applicationId=WebGoat__bcbarbosa -Dclm.serverUrl=https://iq.bbarbosa.eu.ngrok.io/ -Dclm.username=admin -Dclm.password=01021994
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: https://iq.bbarbosa.eu.ngrok.io/
        username: admin
        password: ${{ secrets.01021994 }}
        applicationId: WebGoat__bcbarbosa
        stage: Build
        target: .
        
  
