name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Sonatype CLM for Maven
      run: mvn com.sonatype.clm:clm-maven-plugin:evaluate -Dclm.applicationId=WebGoat__bcbarbosa -Dclm.serverUrl=${{ secrets.iqurl }} -Dclm.username=${{ secrets.iquser }} -Dclm.password=${{ secrets.iqpassword }}

    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@1.1.1
      with:
        serverUrl: ${{ secrets.iqurl }}
        username: ${{ secrets.iquser }}
        password: ${{ secrets.iqpassword }}
        applicationId: WebGoat__bcbarbosa
        stage: Build
        target: .
